---
name: Paul
surname: Johnson
position: "Data Scientist"
address: "School of Physics & Chemistry, École Normale Supérieure"
phone: 07869760968
www: paulrjohnson.net
email: "paul@paulrjohnson.net"
twitter: paul_johnson89
github: paulj1989
linkedin: paulj1989
date: "`r format(Sys.time(), '%B %Y')`"
output: 
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
```

# Some stuff about me

 * I poisoned myself doing research.
 * I was the first woman to win a Nobel prize
 * I was the first person and only woman to win a Nobel prize in two different sciences.

# Education

```{r}
library(tibble)
tribble(
  ~ Degree, ~ Year, ~ Institution, ~ Where,
  "Political Science MA", "1889-91", "University of Houston", "Houston, Texas",
  "Global Politics MSc", "1893", "University of Southampton", "Southampton, United Kingdom",
  "Politics BA Hons", "1894", "University of Sussex", "Brighton, United Kingdom"
) %>% 
  detailed_entries(Degree, Year, Institution, Where)
```

# Work

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>% 
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year, 
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```

